# Generated by Django 3.2.5 on 2021-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210707_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
